M48
; DRILL file {KiCad 7.0.7} date Tue Oct 17 18:40:42 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-17T18:40:42-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X5.0Y-3.13
T2
X4.9457Y-3.6509
X4.9457Y-3.7691
T3
X8.0877Y-3.8534
X8.0877Y-4.0266
T0
M30
